### ISSUE TITLE
[Feature Request] Syncing Tachidesk reading status with Tracking services like MAL, Anilist etc

### ISSUE THREAD

**Issue by arbuilder** [Suwayomi/Suwayomi-Server#80]
## Device information
- Tachidesk version: Docker [arbuild/tachidesk-docker:latest/slim](https://hub.docker.com/r/arbuild/tachidesk-docker)
- Server Operating System: Win 10 Home
- Server Desktop Environment: WSL2 Ubuntu 20.04
- Server JVM version: bundled with docker image 
- Client Web Browser: Google Chrome Version latest.

Currently we lack syncing with any tracking services. It would be good to have syncing your reading status to Mal, Anilist etc services. 

Features to have:

- Offline list with tags like reading/ dropped/ complete on hold etc and fields like rating, last read chapter, last read volume, read start date, completion date etc
- Compare and synchronise local list with tracking sites list
- Edit each services tracking links from manga page.

We can look over the source code of [trackma](https://github.com/z411/trackma) for guidance.

**Comment by arbuilder** [comment]
Since tracking project is mentioned in the tachidesk far future roadmap we could wait for [tachiyomi 1.x services extension](https://github.com/tachiyomiorg/tachiyomi-1.x/issues/10 ) implementation.
Currently we can provide backup import and export with features of point no. 1 and add that in legacy backup (because  proto.gz backup is also in far future) so users will be able to backup and restore without losing their reading history.

**Comment by fullmetal1** [comment]
If I'm not mistaken, it seems like services extension is a will not implement for tachiyomi. arkon's last message on the issue is `Adding/changing trackers doesn't happen too often, so I'm fine with leaving it within the app itself`, and then the bug was closed as complete.

Is there still no intention to implement syncing reading status with tracking services in tachidesk as a bespoke feature?

**Comment by AriaMoradi** [comment]
> Is there still no intention to implement syncing reading status with tracking services in tachidesk as a bespoke feature

Why not, we all want more nice features, but we get new features when people actually make them, so we'll have to wait for it. If you need such a feature so badly then step up with your time or money.

**Comment by fullmetal1** [comment]
I'm asking for clarity on the status of the feature request, not demanding progress.

**Comment by AriaMoradi** [comment]
> I'm asking for clarity on the status of the feature request, not demanding progress.

It will be done when we close this issue.

**Comment by ghost** [comment]
Fucking pathetic its been 4 years

**Comment by Syer10** [comment]
@Elryyyyyyyy None of the developers use tracking all that much, and because this is a still WIP application its not as high priority as other features, if you would like to contribute it feel free, but our focus is on other aspects.

That kind of language is not tolerated here, so I will be hiding your comment.
